plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.45.0
        checksums:
          darwin-amd64: 9387bf3967c0c62e269ccdb0d8992b42619fee75eeb61761b5d9a2e4ab1f4e89
          linux-amd64: 8781ea0b3ee495b78898e254fe40346844af60f9407bc493d7ac313c3df4756b
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.45.0
        checksums:
          darwin-amd64: 86c00f02a2fa80a2223d492e931c4ec3312b3e0c895822c2f5ed8c0ea7b2e1b9
          linux-amd64: ac50a961c95657a92105c417671b8d18dfe45da0019e72cdac0b9f5938f2ea4c
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
